### ISSUE TITLE
Paket Hatası veriyor 

### ISSUE THREAD

**Issue by mehmetsarr** [mertinkotr/shopier-payment#2]
Merhaba hocam, shopierAPI.php deki paket yerine, web sitemizdeki ürünümü yazacağız.

**Comment by mrtsntrk** [comment]
> Merhaba hocam, shopierAPI.php deki paket yerine, web sitemizdeki ürünümü yazacağız.

Kod üzerinde değişiklik yaparak ürünlerinizi yazabilirsiniz.
